# Generated by Django 5.0.1 on 2024-01-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('colour', 'colour'), ('size', 'size')], max_length=100),
        ),
    ]
